# Generated by Django 4.1 on 2022-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaccount',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationaccount',
            name='image_link',
            field=models.CharField(default='https://doctoritas.com/blank-person/?lang=en', max_length=128),
        ),
    ]
