# Generated by Django 4.1 on 2022-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_alter_organizationaccount_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaccount',
            name='image_link',
            field=models.CharField(default='https://doctoritas.com/blank-person/?lang=en', max_length=555),
        ),
    ]
