# Generated by Django 4.1 on 2022-09-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_events_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='Untitled', max_length=64),
        ),
    ]
