# Generated by Django 4.1 on 2022-09-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_alter_organizationaccount_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaccount',
            name='facebook_link',
            field=models.CharField(default='https://www.facebook.com', max_length=555),
        ),
    ]
