# Generated by Django 4.1 on 2022-09-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_articles_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=32)),
                ('program', models.CharField(max_length=32)),
                ('level', models.CharField(max_length=16)),
                ('facebook_link', models.CharField(max_length=64)),
            ],
        ),
    ]
