# Generated by Django 4.1 on 2022-09-12 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_registerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='Untitled', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='registerlist',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 12, 12, 33, 21, 643136)),
        ),
        migrations.AlterUniqueTogether(
            name='registerlist',
            unique_together={('name', 'program', 'level')},
        ),
    ]
