# Generated by Django 4.1 on 2022-09-12 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_alter_articles_title_alter_registerlist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlist',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 12, 4, 34, 29, 861282, tzinfo=datetime.timezone.utc)),
        ),
    ]
