# Generated by Django 4.1 on 2022-09-12 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_alter_registerlist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlist',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 12, 4, 35, 39, 928453, tzinfo=datetime.timezone.utc)),
        ),
    ]
